// Generated by CoffeeScript 1.10.0
(function() {
  var Point;

  this.LazyLoadNS = this.LazyLoadNS || {};

  Point = (function() {
    function Point(x, y) {
      this.x = x;
      this.y = y;
    }

    return Point;

  })();

  LazyLoadNS.Point = Point;

}).call(this);
