// Generated by CoffeeScript 1.8.0
(function() {
  this.Image = (function() {
    function Image(imageElement, _loadingImage) {
      this._loadingImage = _loadingImage;
      this._imageElement = $(imageElement);
    }

    Image.prototype.isInViewPort = function() {
      var element, imageRectangle, viewPortRectangle;
      element = this._imageElement.get(0);
      viewPortRectangle = new Viewport().rectangle();
      imageRectangle = new Rectangle(element.offsetLeft, element.offsetTop, element.width, element.height);
      if (viewPortRectangle.hasCollisionWithRectangle(imageRectangle)) {
        return true;
      }
      return false;
    };

    Image.prototype._isAlreadyCancelled = function() {
      var imgIsCancelled;
      imgIsCancelled = this._imageElement.data("cancelled");
      return imgIsCancelled;
    };

    Image.prototype.cancel = function() {
      var realSrc;
      if (this._isAlreadyCancelled()) {
        return;
      }
      this._imageElement.data("cancelled", true);
      realSrc = this._imageElement.attr("src");
      this._imageElement.get(0).src = this._loadingImage;
      return this._imageElement.attr("data-src", realSrc);
    };

    Image.prototype.show = function() {
      var realSrc;
      realSrc = this._imageElement.attr("data-src");
      this._imageElement.get(0).src = realSrc;
      return this._imageElement.removeAttr("data-src");
    };

    return Image;

  })();

}).call(this);
