// Generated by CoffeeScript 1.8.0
(function() {
  var Point, Rectangle;

  this.LazyLoadNS = this.LazyLoadNS || {};

  Point = LazyLoadNS.Point;

  Rectangle = (function() {
    function Rectangle(left, top, width, height) {
      this.left = left;
      this.top = top;
      this.width = width;
      this.height = height;
    }

    Rectangle.prototype.right = function() {
      return this.left + this.width;
    };

    Rectangle.prototype.bottom = function() {
      return this.top + this.height;
    };

    Rectangle.prototype.hasPointInside = function(point) {
      if (point.x >= this.left && point.x <= this.right() && point.y >= this.top && point.y <= this.bottom()) {
        return true;
      }
      return false;
    };

    Rectangle.prototype.hasCollisionWithRectangle = function(rectangle) {
      var bottomLeftPoint, bottomRightPoint, topLeftPoint, topRightPoint;
      topLeftPoint = new Point(rectangle.left, rectangle.top);
      if (this.hasPointInside(topLeftPoint)) {
        return true;
      }
      topRightPoint = new Point(rectangle.right(), rectangle.top);
      if (this.hasPointInside(topRightPoint)) {
        return true;
      }
      bottomLeftPoint = new Point(rectangle.left, rectangle.bottom());
      if (this.hasPointInside(bottomLeftPoint)) {
        return true;
      }
      bottomRightPoint = new Point(rectangle.right(), rectangle.bottom());
      if (this.hasPointInside(bottomRightPoint)) {
        return true;
      }
      return false;
    };

    return Rectangle;

  })();

  LazyLoadNS.Rectangle = Rectangle;

}).call(this);
