// Generated by CoffeeScript 1.8.0
(function() {
  this.Viewport = (function() {
    function Viewport() {}

    Viewport.prototype.rectangle = function() {
      var height, left, top, width;
      left = window.pageXOffset;
      top = window.pageYOffset;
      width = window.innerWidth;
      height = window.innerHeight;
      return new Rectangle(left, top, width, height);
    };

    return Viewport;

  })();

}).call(this);
